import React from 'react'
import Head from 'next/head'
import styles from '../styles/header.module.scss'
import clsx from  'clsx'



function Essentials() {
  return (
    <div className={styles.container}>
       <Head>
          <title>TrixCode Next_JS</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className={ clsx(styles.header, styles.header_home)}>
              
              <buttton className={styles.header_button} type="button">
                  <span className={styles.header_button_item}>Menu</span>
              </buttton>
              <nav className={styles.header_nav}>
                  <a href="index.html" className={ clsx(styles.header_nav_link, styles.active)}>home</a>
                  <a href="essentials.html" className={styles.header_nav_link}>essentials</a>
                  <a href="" className={styles.header_nav_link}>it peases</a>
                  <a href="" className={styles.header_nav_link}>custom</a>
              </nav>
  
      
         
        </header >
    </div>
  )

}

export default Essentials