import Head from 'next/head'
import styles from '../styles/header.module.scss'



export default function Home() {
  return (
    <div className='body'>
      <Head>
        <title>TrixCode Next_JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header.home}>
        <div className={styles.header_inner}>
            <div className={styles.header_logo}>
                <img src="<%=require('../src/images/logo.svg')%>" alt="logo"></img>
            </div>
            <buttton className={styles.header_button} type="button">
                <span className={styles.header_button_item}>Menu</span>
            </buttton>
            <nav className={styles.header_nav}>
                <a href="index.html" className={styles.header_nav_link.active}>home</a>
                <a href="essentials.html" className={styles.header_nav_link}>essentials</a>
                <a href="" className={styles.header_nav_link}>it peases</a>
                <a href="" className={styles.header_nav_link}>custom</a>
            </nav>

        </div>
        <div className={styles.header_title}><h1 className={styles.title} id="title"><p>err one</p>
                <p>deserves</p>
                <p>to be iced out</p>
            </h1>
        </div>
        <div className={styles.header_footer}>
            <div className={styles.header_social}>
                <a className={styles.header_social_link} href="">instagram</a>
                <a href="">twitter</a>
            </div>
            <div className={styles.header_watch_video}>
                <a href="">watch video</a>
            </div>
        </div>
        <form className={styles.header_form}>
            <div className={styles.slide_submit}>
            </div>
            <button type="submit" className={styles.submit_btn}>
                <img src="<%=require('../src/images/arrow_l.svg')%>" alt=""></img>
                <p>swipe left</p>
              </button> 
             
          </form>
      </header >
    </div>
    
    
    
  )
}
